Repository dreipol/vue-ui, pull requests merged in 2019-01, with the labels that each got.

#9 Feature/forms
  .babelrc
  .circleci/config.yml
  .gitignore
  babel.config.js
  karma.config.js
  package-lock.json
  package.json
  src/components/form/actions/actions.vue
  src/components/form/checkbox/checkbox.spec.js
  src/components/form/checkbox/checkbox.vue
  src/components/form/hidden/hidden.vue
  src/components/form/input/input.spec.js
  src/components/form/input/input.vue
  src/components/form/model-provider/model-provider.spec.js
  src/components/form/model-provider/model-provider.vue
  src/components/form/optgroup/optgroup.vue
  src/components/form/option/option.vue
  src/components/form/radio/radio.spec.js
  src/components/form/radio/radio.vue
  src/components/form/select/select.spec.js
  src/components/form/select/select.vue
  src/components/form/textarea/textarea.spec.js
  src/components/form/textarea/textarea.vue
  src/components/icon/icon.vue
  src/components/intersection-observer/IRegistrationOptions.ts
  src/components/modal/modal.spec.js
  src/components/modal/modal.vue
  src/components/overlay/IOverlay.ts
  src/components/overlay/overlay.spec.js
  src/components/overlay/overlay.vue
  src/mixins/form/current-value/index.js
  src/mixins/form/floating-label-props/index.js
  src/mixins/form/focus-behaviour/index.js
  src/mixins/form/has-errors-props/index.js
  src/mixins/form/is-checked/index.js
  src/mixins/form/root-classes/index.js
  src/mixins/intersection-observer/index.spec.js
  src/mixins/is-mounted/index.js
  src/mixins/is-mounted/is-mounted.spec.js
  src/util/count-virtual-tags/index.js
  src/util/detect/edge-detect/index.js
  src/util/detect/ie-detect/index.js
  test/.eslintrc
Labels: FULL

#13 Feature/component and module updates
  package-lock.json
  src/components/modal/modal.vue
  src/components/overlay/overlay.spec.js
  src/components/overlay/overlay.vue
  src/filters/background-image/index.js
  src/filters/srcset/index.js
  src/index.js
  src/mixins/scroll-lock-helper/index.js
  src/mixins/uuid/index.js
  src/modules/index.js
  src/modules/mutation-types.js
  src/modules/overlay/actions.js
  src/modules/overlay/index.js
  src/modules/overlay/overlay-module.spec.js
  src/modules/scroll/actions.js
  src/modules/scroll/index.js
  src/modules/scroll/mixin.js
  src/modules/scroll/scroll-module.spec.js
  src/presets.js
  src/util/defer/index.js
Labels: ACK

#12 Add the documentation for the input fields
  LICENSE
  README.md
  src/components/README.md
  src/components/form/README.md
  src/components/form/hidden/hidden.vue
  src/components/icon/README.md
  src/components/index.js
  src/components/intersection-observer/README.md
  src/components/modal/README.md
  src/components/modal/modal.spec.js
  src/components/overlay/README.md
  src/components/overlay/overlay.spec.js
  src/components/scroll-reveal/README.md
  src/create-config.js
  src/filters/README.md
  src/filters/background-image/background-image.spec.js
  src/filters/background-image/index.js
  src/filters/index.js
  src/index.js
  src/mixins/README.md
  src/mixins/bem/README.md
  src/mixins/index.js
  src/mixins/intersection-observer/README.md
  src/mixins/is-mounted/README.md
  src/mixins/scroll-lock-helper/README.md
  src/mixins/scroll/index.js
  src/modules/index.js
  src/util/index.js
  src/vuex/README.md
  src/vuex/index.js
  src/vuex/modules/mutation-types.js
  src/vuex/modules/overlay/README.md
  src/vuex/modules/overlay/actions.js
  src/vuex/modules/overlay/getters.js
  src/vuex/modules/overlay/index.js
  src/vuex/modules/overlay/overlay-module.spec.js
  src/vuex/modules/scroll/README.md
  src/vuex/modules/scroll/actions.js
  src/vuex/modules/scroll/index.js
  src/vuex/modules/scroll/scroll-module.spec.js
Labels: FULL

#14 [cleanup] Update the code for v1
  src/components/index.js
  src/components/intersection-observer/README.md
  src/mixins/README.md
  src/mixins/index.js
  src/presets.js
  src/util/README.md
Labels: ACK

#15 Feature/intersection observer unittests
  dist/index.js
  package.json
  src/components/intersection-observer/intersection-observer.spec.js
  src/components/intersection-observer/intersection-observer.vue
Labels: ACK, UNREVIEWED
